#!/usr/bin/env python3
import boto3

from lib import *

# Arguments
if len(sys.argv) < 2:
    print("syntax: cluster-describe <CLUSTER_ID>")
    exit(1)

clusterId = sys.argv[1]

# Initialize Boto3
ec2 = boto3.client('ec2')
route53 = boto3.client('route53')

# List all instances
instances = ec2.describe_instances(Filters=[
    {'Name': 'tag:Name', 'Values': [clusterId]}, 
    {'Name': 'instance-state-name', 'Values': ['running']}])['Reservations']


# Print IP addresses
for instance in instances:
    print(instance['Instances'][0]['InstanceId'])
    print('\t' + instance['Instances'][0]['PrivateIpAddress'])
    print('\t' + instance['Instances'][0]['PublicIpAddress'])
